# Google Cloud Run deployment configuration
service: pakety-grocery-app
runtime: nodejs18

env_variables:
  NODE_ENV: production
  
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 60

resources:
  cpu: 1
  memory_gb: 1

# Health check endpoint
readiness_check:
  path: "/health"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 3
  success_threshold: 2